# This is a basic workflow to help you get started with Actions

name: Master Branch Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [master]
    # Only trigger a workflow when changes have been made to files in the below mentioned path.
    paths:
      - "force-app/**"
env:
  SF_PROD_ORG__AUTH_URL: ${{ secrets.SF_PROD_ORG__AUTH_URL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  Validate_To_PROD:
    runs-on: ubuntu-latest
    container:
      image: sanyamc2304/sfdx-docker-image:latest
      options: --user 0:0 --privileged
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Authorize Org
        run: |
          echo $SF_PROD_ORG__AUTH_URL > authURLFile
          sfdx force:auth:sfdxurl:store -f authURLFile -s -a PROD
      - name: Differential Deployment
        run: |
          sfdx sgd:source:delta --from $(git describe --match "prod-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "prod-*" --abbrev=0 --tags HEAD)---"
          cat package/package.xml
          sfdx force:source:deploy -x package/package.xml --checkonly --testlevel NoTestRun