# This is a basic workflow to help you get started with Actions

name: SIT Branch Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [SIT]
    # Only trigger a workflow when changes have been made to files in the below mentioned path.
    paths:
      - "force-app/**"
env:
  SF_SIT_ORG__AUTH_URL: ${{ secrets.SF_SIT_ORG__AUTH_URL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Deploy_To_SIT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    container:
      image: sanyamc2304/sfdx-docker-image:latest
      options: --user 0:0 --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Authorize Org
        run: |
          echo $SF_SIT_ORG__AUTH_URL > authURLFile
          sfdx force:auth:sfdxurl:store -f authURLFile -s -a SIT
      - name: Differential Deployment
        run: |
          sfdx sgd:source:delta --from $(git describe --match "sit-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "sit-*" --abbrev=0 --tags HEAD)---"
          cat package/package.xml
          sfdx force:source:deploy -x package/package.xml
      - name: create tag
        run: |
          git tag sit-$(date +"%Y%m%d%H%M%S")
          git push --tags

  # This workflow contains a single job called "build"
  Validate_To_UAT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    container:
      image: sanyamc2304/sfdx-docker-image:latest
      options: --user 0:0 --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Authorize Org
        run: |
          echo $SF_UAT_ORG__AUTH_URL > authURLFile
          sfdx force:auth:sfdxurl:store -f authURLFile -s -a UAT
      - name: Differential Deployment
        run: |
          sfdx sgd:source:delta --from $(git describe --match "uat-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "uat-*" --abbrev=0 --tags HEAD)---"
          cat package/package.xml
          sfdx force:source:deploy -x package/package.xml --checkonly